### ISSUE TITLE
[Bug report] Channel topic doesn't get reset

### ISSUE THREAD

**Issue by ndma-ucsc** [jagrosh/MusicBot#1018]
### Is your feature request related to a problem? Please describe.

Channel topic currently stays as the most recent song played.

### What is your ideal solution to the problem?

Clear the channel topic (or to a default status) when the bot leaves the voice channel.

### How would this feature be used?

1. Queue ends or stop/leave command is issued.
2. Bot leaves the voice channel and clears the channel topic or sets channel topic to a default.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
This is a bug, rather than a missing feature. Because Discord introduced a high rate limit for channel topics (2 changes every 15 minutes i think?), we made it so that the MusicBot aborts changing the channel topic when it hits that limit.

It looks like that MusicBot also aborts the "reset" when it hits the rate limit. At the moment, I'm unsure how this could be fixed.

**Comment by prashker** [comment]
Realistically, a feature like this doesn't really work with such a rate limit on Discord side.
