### ISSUE TITLE
Always high ping and audio stutter

### ISSUE THREAD

**Issue by Weedley** [jagrosh/MusicBot#124]
Hi, thank you for the musicbot! I also gut the high ping and stutter problem. I am using a raspberry pi 3, it runs perfectly smooth and the CPU is not even close to high usage. The pi is connected via ethernet cable to a very good internet connection. The Discord region is set to the best and nearest to me.
I Followed all instructions even the additional instructions and i've read all isues before. I can't find out what makes out this huge lags. Didn't had that with other music bots but i'd like to use this one. I am very thankfull for anyone who can help! Thanks.

**Comment by jagrosh** [comment]
Just double checking, you've followed the additional instructions from [this page](https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi), right? Also checking, which version of the bot are you running? (it's listed in the `about` command).

**Comment by Weedley** [comment]
Yes i double checked, it's all set. Bot is running on v0.1.1

**Comment by Rikusen0335** [comment]
I have same issue but I am using bot on Ubuntu Server.
And running on v0.1.2 .

**Comment by jagrosh** [comment]
If you are using the [latest version](https://github.com/jagrosh/MusicBot/releases/latest) (and if on Raspberry Pi, the Linux jar), if you continue to have high ping and stutter, the issue is likely your internet connection, the bot's internet connection, or both. Also try changing voice regions within Discord and lowering the bitrate on your voice channel.
