### ISSUE TITLE
[Bug Report] Newly added songs get preferred in queue than already added songs.

### ISSUE THREAD

**Issue by mawen-fn** [jagrosh/MusicBot#1320]
### Bug Description

When I am in a voice chat and other users add songs after I added mine, they get often get preferred.

### Steps to Reproduce

1. Add a song to queue
2. Different user adds a song

### Expected Result

I expected my song to play first because I added it first.

### Debug Output

```
System Properties:
  java.version = 11.0.17
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.17+8-post-Ubuntu-1ubuntu222.04
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.9
  Owner = 615294935242899486
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 127
  Used Memory = 50

Discord Information:
  ID = 968253751263625236
  Guilds = 1
  Users = 3
```

### Additional Info

In all cases moderators are also online using the voice chat.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This is not a bug. JMusicBot uses a "FairQueue" which automatically distributes songs added to the queue by user so that no user can single-handedly hog the queue. Among songs you've added, they will remain linear, but in terms of the entire queue, the songs will play in-turn per user.

For example, let's say that the current queue contains 7 songs from user A:
`AAAAAAA`
If user B adds 3 songs, and then user C adds 1 song, the queue will look like this:
`ABCABABAAAA`
