### ISSUE TITLE
[Feature Request] remove "Private Bot" to the mandatory pre-startup check

### ISSUE THREAD

**Issue by MrZoyo** [jagrosh/MusicBot#1507]
### Is your feature request related to a problem? Please describe.

I'm glad that 0.4.0 fixes a big problem with the previous version. But I noticed that in 0.4.0, compared to 0.3.9, it forces your discord to be private bot or it won't be allowed to start. For some reason my bot is a public bot and can't be changed to a private bot. i know it can be corrupted if run on too many servers, but that's not a problem for me. So I can't use 0.4.0 at all right now.

### What is your ideal solution to the problem?

It might be possible to set it up as before, as a warning rather than a mandatory startup condition.

### How would this feature be used?

This way a lot of people who can't switch to private bot can also continue to use 0.4.0

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This isn't going to be changed

**Comment by Steanky** [comment]
@MrZoyo @sks316 @suchmememanyskill Since @jagrosh seems committed to keeping in this anti-feature, I've forked the project [here](https://github.com/Steanky/MusicBot) and enabled support for non-private bots. I also *need* to use JMusicBot as a public bot because I share my bot with a small friend group, and I am not in all of the servers they are.

It's a shame, because this project is easily the best self-hosted music bot option out there and is otherwise very well made.

**Comment by sks316** [comment]
@Steanky Thanks for letting me know, but [I've also actually made my own fork already](https://github.com/sks316/MusicBot). I'm in a similar situation, where I share it with my friends but I'm not in all of their servers, and I feel the solution proposed by jagrosh (enabling it temporarily while the bot is running so your friend can add it) feels like an unnecessary hacky workaround to a problem that didn't exist in the first place.

**Comment by suchmememanyskill** [comment]
> @MrZoyo @sks316 @suchmememanyskill Since @jagrosh seems committed to keeping in this anti-feature, I've forked the project [here](https://github.com/Steanky/MusicBot) and enabled support for non-private bots. I also *need* to use JMusicBot as a public bot because I share my bot with a small friend group, and I am not in all of the servers they are.
> 
> It's a shame, because this project is easily the best self-hosted music bot option out there and is otherwise very well made.

I don't need to disable the feature, just very annoyed that i found my instance bootlooping as my bot automatically updates, due to what is arguably kind of dumb feature :/

**Comment by Hartie95** [comment]
The changelog should at least clearly state that it will shut itself down in these cases, instead of it just being more "warnings".
This is not a warning, this is a fatal the way its implemented.

Also why was it done this way in the first place? I mean showing a warning and denying support, ok, but why fatal in that case, when it doesn't even seem to be breaking in any way. 
Also why so hidden? Properly announce it, and best also give a reason why, when it potentially breaks setups.

Another potential solution would have been to add a startup parameter or settings config to overwrite it, with the full knowledge of not getting support in that case.

**Comment by coolpeter98** [comment]
I literally have no idea why Jagrosh added this anti-feature, it should be our decision whether we want the bot to be private or not.

**Comment by Gurkengewuerz** [comment]
I guess every answer is completely ignored by josh instead of being open for discussions?
