### ISSUE TITLE
Bot Sometimes Adds Songs Into Middle of Queue Rather Than End

### ISSUE THREAD

**Issue by benzarr410** [jagrosh/MusicBot#16]

**Comment by jagrosh** [comment]
If you take a look at the `about` command, you'll see one of the things listed is "FairQueue Technology"; that actually isn't a joke. When users add songs, their songs always get added after _their_ other songs, but they will be dispersed in between other users' songs, so that everyone can hear their music and no single person can hog the queue.

If you are the only person adding songs, they will always be added to the end. If one person has a lot of songs in the queue, and a second person starts adding songs, their songs will be placed at position 2, 4, 6, etc. If a third person begins adding songs, they will be placed in spot 3, 6, 9, etc.
