### ISSUE TITLE
[Bug Report] Bot crashes upon loading GUI when wrong token type was used instead of telling the user that the wrong token type was used.

### ISSUE THREAD

**Issue by Mamumimi** [jagrosh/MusicBot#199]
After upgrading from a previous version, I had encountered some problems with the bot. Namely, certain commands not working or the bot joining the voice channel and not doing anything. I elected to reinstall the bot from scratch (deleting all configs in the folder containing the jar and replacing with a fresh install). The bot now closes itself immediately upon opening the GUI.

OS: Win10 pro x64, using the windows jar. Let me know of anything else you need to know to be able to help out.

**Comment by Mamumimi** [comment]
I had at the time, though I wiped everything because I do that when I get frustrated with software, lol. I just loaded up 0.1.3 and it tells me that my bot token is invalid, despite it being the same token I've been using. Cleared the config and re-pasted the token, says it's still invalid.

**Comment by Mamumimi** [comment]
Closed because I'm a moron. Sorry for wasting your time.

**Comment by jagrosh** [comment]
Closing because there's not really any way to detect a "different type of token" from simply an "invalid token"; any input that's not a valid bot token is just an invalid bot token, and I think the error message that is provided (that the token is invalid) should be enough to indicate that the user needs to go and retrieve the correct token. Deleting the token from the config file would also prompt for it the next time the bot starts, with a link to instructions for how to obtain it.
