### ISSUE TITLE
[Feature Request] A way to get the token form a .txt file (e.g. 'token.txt')

### ISSUE THREAD

**Issue by IpProxyNeon** [jagrosh/MusicBot#276]
I'd like to suggest a way to get the token from .txt file since it is more convenient for people to run their bot if they are using more then one bot (Like me since my bot is currently written in python and I'm working on a NodeJS command aswell now)

**Comment by jagrosh** [comment]
[There is already a token field in the config file](https://github.com/jagrosh/MusicBot/wiki/Example-Config), so I'm unsure what you mean.

**Comment by jagrosh** [comment]
Also, there are many ways to use different tokens for different bots:
- You could use a different config file for each, and specify the config file on the command line (`-Dconfig=/path/to/config/file`)
- You could specify the token on the command line instead of in the config file (`-Dtoken=BOT_TOKEN`)
- You could set the token in an environment variable
