### ISSUE TITLE
[Bug Report] Scratchy playback and high ping for some reason?

### ISSUE THREAD

**Issue by ionite34** [jagrosh/MusicBot#329]
High ping and scratchy playback? Playback sounds 'scratchy' and has stutters. Running ping command returns "Ping: 204ms | Websocket: 207ms" despite being hosted locally (tried on local pc as well as local Linux server), my connection to the discord server my server is running on (as shown when I'm in a voice channel in the server) is 3ms, packet loss 0%. 

Not sure what the problem might be, debug attached. (Running on PC at the moment)

[debug_information.txt](https://github.com/jagrosh/MusicBot/files/3883272/debug_information.txt)

**Comment by sammyhwang** [comment]
My local connection to most major websites and servers is between 3-4ms. And I'm running on a gigabit fiber connection.

**Comment by peterthehan** [comment]
Happens to me occasionally too, what usually "fixes" it for me is to switch between different server regions. I typically default to US East, but rotate between US Central and US South when it gets scratchy.

**Comment by slaapkopamy** [comment]
hi, I have the same problem in europe, multiple discord servers other regions.. I'm running always via the same linux server where i run another bots on it before i never had any problems but its a recent one. ping it says between 100 - 150 ms what is normal for it because it doesn't go lower somehow... basicly i cannot use the bot right now :/

**Comment by jagrosh** [comment]
Most of the time, this is a Discord issue; there's nothing in the bot I can really change to prevent this.
