### ISSUE TITLE
[Bug Report] DJ permission

### ISSUE THREAD

**Issue by Tavinen** [jagrosh/MusicBot#366]
**Is your feature request related to a problem? Please describe.**
The permission for DJ always resets everytime I restart the bot and I'm tired of the discord leader kicking the bot just because DJ command is not applied on him

**Describe the solution you'd like**
Permanent DJ permission to the selected members even if the bot has restarted

**Describe the basic flow/steps of using this feature**
How this feature would be used:
Make permanent permission for other user in discord channel

**Comment by jagrosh** [comment]
On what platform are you running the bot, and can you provide the output of the `debug` command

**Comment by Tavinen** [comment]
I'm running it on Windows 10 64 bit and here's debug
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/4362386/debug_information.txt)

**Comment by jagrosh** [comment]
The problem is that serversettings.txt isn't getting written, so likely you're not running java with sufficient permissions. You need to make sure that you're running it with sufficient perms to write to wherever you're running it from. My guess is that you're running it on the desktop or some other protected folder; make a folder in a writable directory and try running it from there.
