### ISSUE TITLE
[Bug Report] Now Playing keeps failing

### ISSUE THREAD

**Issue by meltedprocessor** [jagrosh/MusicBot#433]
I've previously reported this but got told Discord had issues and to report again at a later date.

After many more days and seeing no issues with Discord I'm reporting again.

After no more than 4 hours the m!np command fails and stops reporting now playing tracks to the Discord server. I'm running the latest 0.2.9 Linux release on an ubuntu OVH server. Granted low spec but given it's load I wouldn't have thought this would be the issue.  See debug data from bot below.

```
System Properties:
  java.version = 1.8.0_242
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_242-8u242-b08-1~deb9u1-b08
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.9
  Owner = xxxx
  Prefix = m!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.49

Runtime Information:
  Total Memory = 31
  Used Memory = 29

Discord Information:
  ID = xxxx
  Guilds = 2
  Users = 19
```

**Comment by jagrosh** [comment]
The only reasons the nowplaying output would stop updating would be:
 - the queue ends
 - updating times out (usually due to a connection issue on discord's end)
 - updating fails due to a permissions issue or the message being deleted
 - the bot is shut down

Based on your description, it's just the message timing out at some point, which is usually Discord's fault, and is fairly expected to happen.
