### ISSUE TITLE
user stopped music outside vc

### ISSUE THREAD

**Issue by needhamgary** [jagrosh/MusicBot#434]
I started playing music in a server and a user that wasn't in VC was able to stop the music with the regular stop command. Can this be resolved?

**Comment by jagrosh** [comment]
The stop command is only usable by users with the DJ role, and you should set the DJ role to a role that you trust to manage the queue (for example, most servers set this to their moderator role). It is intentional that users with the elevated permission of using DJ commands can use them without having to join the VC.
