### ISSUE TITLE
[Feature Request] Ability to login to youtube via the bot

### ISSUE THREAD

**Issue by johncsuti** [jagrosh/MusicBot#473]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to login for private playlists and for ad mitigation for users with youtube premium.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
Run a command it tells you to open a link and links music bot with your youtube login.

**Additional context**
Not sure if it is possible.

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
Yes

**Comment by jagrosh** [comment]
If if what you're describing is technically possible (I don't know if 3rd-party apps can access your playlists), JMusicBot doesn't use the YouTube API, so adding something like this would have massive overhead (more dependencies, bigger file size, more setup, more tokens, etc). Additionally, ad mitigation is irrelevant because JMusicBot doesn't stream the ads anyway.

The net result of your suggestion, if it were possible, would be being able to access private playlists and videos, but considering the downsides, I think you'd be better off just making unlisted playlists/videos and linking them directly, which incurs none of the aforementioned overhead.
