### ISSUE TITLE
[Feature Request] Ability to disable Youtube playlists

### ISSUE THREAD

**Issue by DisturbedTK** [jagrosh/MusicBot#485]
Can we have a feature that disables youtube playlists? It's quite annoying when users add 200 song playlists to the bot. We simply don't need youtube playlists.

**Comment by jagrosh** [comment]
Can you elaborate on what specifically about this you find annoying? Generally, I think playlists are very useful, as they reduce the number of commands needed for knowledgeable users. Also, because the bot uses a fair queue, one user adding many songs won't prevent everyone else's music from being heard. One potential annoyance I can think of is someone adding a lot of songs to the queue and then leaving the voice channel, although I think a better solution than disabling playlists entirely would be a feature to auto-clear users' songs when they are absent from voice for a period of time.

**Comment by mikakoi** [comment]
It's just very weird allowing users to play any playlist on Youtube when local playlists can only be created by owner. 
Having playlist permissions for a basic user is too much power, especially when you're dealing with a server size of ours (around 400k)
Just today we had someone queue 200 wario meme videos on the bot and nobody wanted to join the vc because of that, and of course moderators weren't pinged.

**Comment by DisturbedTK** [comment]
It's just very weird allowing users to play any playlist on Youtube when local playlists can only be created by owner. 
Having playlist permissions for a basic user is too much power, especially when you're dealing with a server size of ours (around 400k)
Just today we had someone queue 200 wario meme videos on the bot and nobody wanted to join the vc because of that, and of course moderators weren't pinged.

**Comment by jagrosh** [comment]
Local playlists can only created by the owner because making local playlists affects the filesystem on the host's computer or server; playing uploaded playlist files would be a reasonable feature to add. Regardless, the functionality of local playlists is unrelated to this issue.

It seems like in your case, your members need to be more proactive in alerting moderators to users with malicious intent. There's nothing that would have stopped the user from adding multiple "meme videos" one-by-one, and in either case (a playlist or multiple individual additions), a moderator can clean up all of that user's additions to the queue with a single command anyway.

I run several servers on the same scale as yours, and on the rare occasions that someone does try to troll, adding a full playlist is no more malicious than just adding a few troll videos, as once someone reports it (usually on the first troll track), it's all cleaned up by a moderator the same way.

**Comment by jagrosh** [comment]
Another way of looking at the situation is that no amount of queue limitations could have fixed your issue if nobody reported it, as the bad actor could have simply kept queuing up meme videos whenever one ended.

**Comment by DisturbedTK** [comment]
I'm sure the situation would have been very different if the person kept spamming his videos, in this situation a person simply did one command and disappeared. If someone is actively breaking the rules, that has higher chance of being reported than a single command that disappears in the message history

**Comment by madman2021** [comment]
I would also like to see a max count for playlists, or even queue limit.
So only allow a user to have a queue of x size. Let's say 20 songs.

Or atleast allow a settings to prevent massive playlists, yes moderators could manually clear it. But it's easier to have it self managed than requireing moderator input.

Would you accept a pull request for something like this ?

**Comment by jagrosh** [comment]
If you're relying on reports/moderators: I don't see why people would be more or less likely to report someone because of more messages. If someone is trying to listen to the queue, then I would imagine that they wouldn't even consider the messages sent by a user, but rather their audio being interrupted by meme tracks, in which case they can simply check who has queued up the meme track and report it.

If you're trying not to rely on moderators: a limit on tracks has zero effect, as someone can simply queue up a new track whenever one of theirs finishes. The order in which different people queue up tracks doesn't affect the play order anyway, as the tracks get sorted based on who adds them. 

While I do agree that people queuing up troll-tracks is a problem, I don't think limiting the queue or disabling playlists solves this problem. I'm sure there is another solution out there that does solve this problem, while not causing inconveniences for average users.

**Comment by jagrosh** [comment]
For example (this is a really rough outline of an idea), imagine an per-user auto-skip feature, where User A can somehow automatically vote to skip tracks from User B (as if they used the skip command every time a track from User B came up). If a user is adding problematic tracks to the queue, the users that are trying to listen could still report them to a moderator, but this would give them a tool in the meantime to manage the tracks (as a group) without needing immediate moderator action. This kind of feature might also encourage use of the skip feature when appropriate (maybe after the 3rd time User A attempts to skip a User B track, it prompts them to enable auto-skip).
