### ISSUE TITLE
Can't loop if you aren't DJ

### ISSUE THREAD

**Issue by Emv2005** [jagrosh/MusicBot#592]
A couple of members in my server using the bot can't use the repeat command without being DJ. I don't wanna give EVERYONE the DJ role.

**Comment by MichailiK** [comment]
Repeat is a DJ command & right now you can't change which commands require DJ.

**Comment by jagrosh** [comment]
In the future, please use one of the provided issue templates. As already stated, the repeat command is only for users with the DJ role. If you wanted to make everyone a DJ without giving everyone a role, you can set the DJ role to @ everyone. Otherwise, you will need to give the DJ role to everyone that you want to be able to enable repeat mode.
