### ISSUE TITLE
Spotify doesn't play

### ISSUE THREAD

**Issue by snoopyisgay** [jagrosh/MusicBot#786]
I just started using this and i realized that spotify and spotify playlists do not play. I don't know if its a problem from my side or it was just not integrated within the bot. But if you could have spotify api, it would be great

**Comment by funforgiven** [comment]
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

Playing from Spotify is not possible, for three main reasons:

1. This would require an additional API key to look up songs on Spotify, which would be confusing for some users and overall make the bot feel more complicated to use.
2. Streaming from Spotify isn't allowed, so the bot would have to "guess" and just play the closest match from YouTube, which is unreliable at best.
3. Discord already has native support for syncing up Spotify playlists between users, so there's no reason to not just use that (and get better audio anyway from Spotify instead of from a Discord voice channel).
